apiVersion: v2
icon: https://helm.sh/img/helm.svg
name: wkhtmltopdf
version: 1.0.1
description: web service for converting HTML to PDF using wkhtmltopdf
maintainers:
- name: maksim-paskal  # Maksim Paskal
  email: paskal.maksim@gmail.com
