replicas: 1

fullNameOverwrite: ""

type: qt

image: paskalmaksim/wkhtmltopdf:v0.0.5-{{ .Values.type }}
imagePullPolicy: IfNotPresent

runAsUser: 1000

podLabels: {}
podAnnotations: {}

nodeSelector: {}
tolerations: []
affinity: {}

pdb:
  enabled: false
  maxUnavailable: 1

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  averageUtilization: 90

resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    memory: 1Gi

ingress:
  enabled: false
  host: wkhtmltopdf-test.domain.com
  annotations: {}
