run:
  timeout: 5m
issues:
  fix: true
linters-settings:
  lll:
    line-length: 200
linters:
  enable-all: true
  disable:
  - execinquery
  - gomnd
  - varnamelen
  - exhaustruct
  - depguard
  - gochecknoglobals