apiVersion: v1
kind: Service
metadata:
  name: {{ include "wkhtmltopdf.fullname" . }}
  labels:
    app: {{ include "wkhtmltopdf.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ include "wkhtmltopdf.fullname" . }}