apiVersion: v1
kind: Service
metadata:
  name: wkhtmltopdf
  labels:
    app: wkhtmltopdf
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: wkhtmltopdf